// Tests generated by Claude (Limited access to codebase, so tests are not biased)

// Test suite for the math expression parser.
// Adjust `parse`, `tree`, and `evaluate` to match your actual function names.
use rustcalculator::parser::{tree, parse};
use rustcalculator::evaluate::eval;
#[cfg(test)]
mod tests {
    use super::*;

    fn run(input: &str) -> f64 {
        eval(&tree(&parse(input)))
    }

    // Helper for float comparisons — avoids flaky failures from f64 rounding
    fn assert_close(actual: f64, expected: f64) {
        assert!(
            (actual - expected).abs() < 1e-9,
            "expected {}, got {}",
            expected,
            actual
        );
    }

    // ---- Basic arithmetic, no precedence tricks ----

    #[test]
    fn test_single_number() {
        assert_close(run("5"), 5.0);
    }

    #[test]
    fn test_simple_add() {
        assert_close(run("2 + 3"), 5.0);
    }

    #[test]
    fn test_simple_sub() {
        assert_close(run("5 - 3"), 2.0);
    }

    #[test]
    fn test_simple_mult() {
        assert_close(run("4 * 3"), 12.0);
    }

    #[test]
    fn test_simple_div() {
        assert_close(run("10 / 4"), 2.5);
    }

    #[test]
    fn test_simple_pow() {
        assert_close(run("2 ^ 3"), 8.0);
    }

    // ---- Precedence ----

    #[test]
    fn test_mult_before_add() {
        assert_close(run("2 + 3 * 4"), 14.0);
    }

    #[test]
    fn test_add_before_mult_reordered() {
        assert_close(run("3 * 4 + 2"), 14.0);
    }

    #[test]
    fn test_pow_before_mult() {
        assert_close(run("2 * 3 ^ 2"), 18.0); // 2 * 9
    }

    #[test]
    fn test_pow_before_add() {
        assert_close(run("1 + 2 ^ 3"), 9.0); // 1 + 8
    }

    #[test]
    fn test_div_and_mult_left_to_right() {
        assert_close(run("8 / 4 * 2"), 4.0); // (8/4)*2, not 8/(4*2)
    }

    #[test]
    fn test_sub_and_add_left_to_right() {
        assert_close(run("10 - 3 + 2"), 9.0); // (10-3)+2, not 10-(3+2)
    }

    #[test]
    fn test_multiple_same_precedence() {
        assert_close(run("2 + 3 + 4 + 5"), 14.0);
    }

    #[test]
    fn test_full_precedence_chain() {
        assert_close(run("2 + 3 * 4 ^ 2"), 50.0); // 2 + 3*16
    }

    // ---- Unary minus ----

    #[test]
    fn test_unary_minus_simple() {
        assert_close(run("-5"), -5.0);
    }

    #[test]
    fn test_unary_minus_in_add() {
        assert_close(run("-3 + 4"), 1.0);
    }

    #[test]
    fn test_unary_minus_after_operator() {
        assert_close(run("2 * -3"), -6.0);
    }

    #[test]
    fn test_unary_minus_after_add() {
        assert_close(run("2 + -3"), -1.0);
    }

    #[test]
    fn test_double_negative() {
        assert_close(run("- -5"), 5.0);
    }

    #[test]
    fn test_subtract_negative() {
        assert_close(run("2 - -3"), 5.0);
    }

    #[test]
    fn test_triple_negative() {
        assert_close(run("- - -5"), -5.0);
    }

    // ---- Unary minus + power interaction (the tricky ones) ----

    #[test]
    fn test_negative_base_power() {
        assert_close(run("-4 ^ 2"), -16.0); // -(4^2), not (-4)^2
    }

    #[test]
    fn test_negative_exponent() {
        assert_close(run("2 ^ -3"), 0.125); // 2^(-3)
    }

    #[test]
    fn test_negative_base_and_exponent() {
        assert_close(run("-2 ^ -3"), -0.125); // -(2^-3)
    }

    #[test]
    fn test_negative_in_mult_with_power() {
        assert_close(run("3 * -4 ^ 2"), -48.0); // 3 * -(4^2)
    }

    // ---- The big combined regression case from earlier ----

    #[test]
    fn test_full_expression_regression() {
        assert_close(run("2 + 3 * -4 ^ 2 - -6 / 2"), -43.0);
    }

    // ---- Nested groups (parens), if your splitter supports them ----

    #[test]
    fn test_simple_grouping() {
        assert_close(run("(2 + 3) * 4"), 20.0);
    }

    #[test]
    fn test_nested_grouping() {
        assert_close(run("((2 + 3) * 4) - 1"), 19.0);
    }

    #[test]
    fn test_grouping_with_unary() {
        assert_close(run("-(2 + 3)"), -5.0);
    }

    #[test]
    fn test_grouping_overrides_precedence() {
        assert_close(run("2 * (3 + 4)"), 14.0); // without parens would be 2*3+4=10
    }

    // ---- Decimals ----

    #[test]
    fn test_decimal_numbers() {
        assert_close(run("2.5 + 1.5"), 4.0);
    }

    #[test]
    fn test_decimal_division() {
        assert_close(run("1 / 3"), 0.3333333333333333);
    }

    // ---- Zero-related edge cases ----

    #[test]
    fn test_zero_add() {
        assert_close(run("0 + 5"), 5.0);
    }

    #[test]
    fn test_zero_mult() {
        assert_close(run("5 * 0"), 0.0);
    }

    #[test]
    fn test_pow_zero_exponent() {
        assert_close(run("5 ^ 0"), 1.0);
    }

    #[test]
    fn test_zero_pow_zero() {
        assert_close(run("0 ^ 0"), 1.0); // most conventions define this as 1
    }

    // NOTE: division by zero — decide what your calculator SHOULD do here
    // (panic, return infinity, or a Result::Err) before writing this test.
    // f64 division by zero in Rust returns `inf`, not a panic, by default:
    // #[test]
    // fn test_div_by_zero() {
    //     assert!(run("5 / 0").is_infinite());
    // }
}